/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        new Splash(this,true).setVisible(true);
        init();
        initClock();
    }
    
    void init() {
        this.setLocationRelativeTo(null);
        setTitle("HỆ THỐNG QUẢN LÝ NHÂN VIÊN");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private Timer timer;

    private void initClock() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
                Date date = new Date();
                lblDongHo.setText(formatter.format(date));
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnTaiKhoan = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnChucVu = new javax.swing.JButton();
        btnPhongBan = new javax.swing.JButton();
        btnHopDong = new javax.swing.JButton();
        btnUngVien = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnThongKe = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JMenuItem();
        mniDoiMk = new javax.swing.JMenuItem();
        mniKetThuc = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniNhanVien = new javax.swing.JMenuItem();
        mniUngVien = new javax.swing.JMenuItem();
        mniPhongBan = new javax.swing.JMenuItem();
        mniChucVu = new javax.swing.JMenuItem();
        mniLoaiHd = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniTaiKhoan = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniSLUV = new javax.swing.JMenuItem();
        mniTuoi = new javax.swing.JMenuItem();
        mniLuong = new javax.swing.JMenuItem();
        mniSLLHD = new javax.swing.JMenuItem();
        mniSLCV = new javax.swing.JMenuItem();
        mniSLPB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/sig-out.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);

        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/ket-thuc.png"))); // NOI18N
        btnKetThuc.setText("Kết thúc");
        btnKetThuc.setFocusable(false);
        btnKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKetThuc);
        jToolBar1.add(jSeparator1);

        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/account.png"))); // NOI18N
        btnTaiKhoan.setText("Tài khoản");
        btnTaiKhoan.setFocusable(false);
        btnTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTaiKhoan);

        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/nhan-vien.png"))); // NOI18N
        btnNhanVien.setText("Nhân viên");
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNhanVien);

        btnChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/chuc_vu.png"))); // NOI18N
        btnChucVu.setText("Chức vụ");
        btnChucVu.setFocusable(false);
        btnChucVu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChucVu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChucVuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChucVu);

        btnPhongBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/phong-ban.png"))); // NOI18N
        btnPhongBan.setText("Phòng ban");
        btnPhongBan.setFocusable(false);
        btnPhongBan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPhongBan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongBanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPhongBan);

        btnHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/hop-dong.png"))); // NOI18N
        btnHopDong.setText("Hợp đồng");
        btnHopDong.setFocusable(false);
        btnHopDong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHopDong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHopDongActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHopDong);

        btnUngVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/ung-vien.png"))); // NOI18N
        btnUngVien.setText("Ứng viên");
        btnUngVien.setFocusable(false);
        btnUngVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUngVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUngVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUngVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUngVien);
        jToolBar1.add(jSeparator2);

        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/thong-ke.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThongKe);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Info.png"))); // NOI18N
        jLabel2.setText("HỆ THỐNG QUẢN LÝ NHÂN VIÊN");

        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Clock.png"))); // NOI18N
        lblDongHo.setText("00:00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDongHo))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        Desktop.setBackground(new java.awt.Color(204, 204, 204));
        Desktop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        mnuHeThong.setText("Hệ thống");

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/sig-out.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);

        mniDoiMk.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mniDoiMk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/doi_mat_khau.png"))); // NOI18N
        mniDoiMk.setText("Đổi mật khẩu");
        mniDoiMk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMkActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMk);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mniKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/ket-thuc.png"))); // NOI18N
        mniKetThuc.setText("Kết thúc");
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniKetThuc);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setText("Quản lý");

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/nhan-vien.png"))); // NOI18N
        mniNhanVien.setText("Nhân viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniNhanVien);

        mniUngVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniUngVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/ung-vien.png"))); // NOI18N
        mniUngVien.setText("Ứng viên");
        mniUngVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUngVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniUngVien);

        mniPhongBan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniPhongBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/phong-ban.png"))); // NOI18N
        mniPhongBan.setText("Phòng ban");
        mniPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPhongBanActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniPhongBan);

        mniChucVu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/chuc_vu.png"))); // NOI18N
        mniChucVu.setText("Chức vụ");
        mniChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChucVuActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniChucVu);

        mniLoaiHd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniLoaiHd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/hop-dong.png"))); // NOI18N
        mniLoaiHd.setText("Loại hợp đồng");
        mniLoaiHd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoaiHdActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniLoaiHd);
        mnuQuanLy.add(jSeparator3);

        mniTaiKhoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/account.png"))); // NOI18N
        mniTaiKhoan.setText("Tài khoản");
        mniTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTaiKhoanActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniTaiKhoan);

        jMenuBar1.add(mnuQuanLy);

        mnuThongKe.setText("Thống kê");

        mniSLUV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniSLUV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/ung-vien.png"))); // NOI18N
        mniSLUV.setText("Số lượng ứng viên");
        mnuThongKe.add(mniSLUV);

        mniTuoi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniTuoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/age.png"))); // NOI18N
        mniTuoi.setText("Nhân viên theo độ tuổi");
        mnuThongKe.add(mniTuoi);

        mniLuong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/salary.png"))); // NOI18N
        mniLuong.setText("Nhân viên theo lương");
        mnuThongKe.add(mniLuong);

        mniSLLHD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniSLLHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/hop-dong.png"))); // NOI18N
        mniSLLHD.setText("Nhân viên theo loại hợp đồng");
        mnuThongKe.add(mniSLLHD);

        mniSLCV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniSLCV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/chuc_vu.png"))); // NOI18N
        mniSLCV.setText("Nhân viên theo chức vụ");
        mnuThongKe.add(mniSLCV);

        mniSLPB.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniSLPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/phong-ban.png"))); // NOI18N
        mniSLPB.setText("Nhân viên theo phòng ban");
        mnuThongKe.add(mniSLPB);

        jMenuBar1.add(mnuThongKe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        DangXuat();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        // TODO add your handling code here:
        openAccountManagement();
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        openEmployeeManagement();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChucVuActionPerformed
        // TODO add your handling code here:
        openPositionManagement();
    }//GEN-LAST:event_btnChucVuActionPerformed

    private void btnPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongBanActionPerformed
        // TODO add your handling code here:
        openDepartmentManagement();
    }//GEN-LAST:event_btnPhongBanActionPerformed

    private void btnHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHopDongActionPerformed
        // TODO add your handling code here:
        openContractManagement();
    }//GEN-LAST:event_btnHopDongActionPerformed

    private void btnUngVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUngVienActionPerformed
        // TODO add your handling code here:
        openCandidateManagement();
    }//GEN-LAST:event_btnUngVienActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        openStatistics();
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
        DangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniDoiMkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMkActionPerformed
        openChangePassword();
    }//GEN-LAST:event_mniDoiMkActionPerformed

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        // TODO add your handling code here:
        openEmployeeManagement();
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void mniUngVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUngVienActionPerformed
        // TODO add your handling code here:
        openCandidateManagement();
    }//GEN-LAST:event_mniUngVienActionPerformed

    private void mniPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPhongBanActionPerformed
        // TODO add your handling code here:
        openDepartmentManagement();        
    }//GEN-LAST:event_mniPhongBanActionPerformed

    private void mniChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChucVuActionPerformed
        // TODO add your handling code here:
        openPositionManagement();
    }//GEN-LAST:event_mniChucVuActionPerformed

    private void mniLoaiHdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoaiHdActionPerformed
        // TODO add your handling code here:
        openContractManagement();
    }//GEN-LAST:event_mniLoaiHdActionPerformed

    private void mniTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTaiKhoanActionPerformed
        // TODO add your handling code here:
        openAccountManagement();
    }//GEN-LAST:event_mniTaiKhoanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        openLogin();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton btnChucVu;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHopDong;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhongBan;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnUngVien;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JMenuItem mniChucVu;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMk;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniLoaiHd;
    private javax.swing.JMenuItem mniLuong;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniPhongBan;
    private javax.swing.JMenuItem mniSLCV;
    private javax.swing.JMenuItem mniSLLHD;
    private javax.swing.JMenuItem mniSLPB;
    private javax.swing.JMenuItem mniSLUV;
    private javax.swing.JMenuItem mniTaiKhoan;
    private javax.swing.JMenuItem mniTuoi;
    private javax.swing.JMenuItem mniUngVien;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    // End of variables declaration//GEN-END:variables
    public void openLogin(){
        Login a = new Login();
        openWindow(Desktop, a);
    }
    
    public void DangXuat(){
        JInternalFrame[] frames = Desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
        }
        openLogin();
    }
    
    public void openPositionManagement(){
        PositionManagement a = new PositionManagement();
        openWindow(Desktop, a);    
    }
    
    public void openContractManagement(){
        ContractManagement a = new ContractManagement();
        openWindow(Desktop, a);    
    }
    
    public void openEmployeeManagement(){
        EmployeeManagement a = new EmployeeManagement();
        openWindow(Desktop, a);    
    }
    
    public void openDepartmentManagement(){
        DepartmentManagement a = new DepartmentManagement();
        openWindow(Desktop, a);    
    }
    
    public void openAccountManagement(){
        AccountManagement a = new AccountManagement();
        openWindow(Desktop, a);        
    }
    
    public void openCandidateManagement(){
        CandidateManagement a = new CandidateManagement();
        openWindow(Desktop, a);
    }
    public void openStatistics() {
                Statistics a = new Statistics();
                openWindow(Desktop, a);
                //tk.selectTab(index);
    }
    
    public void openChangePassword() {
        ChangePassword a = new ChangePassword();
        openWindow(Desktop, a);
    }
    
    private void openWindow(JDesktopPane desktopPane, JInternalFrame jInternalFrame){
        Dimension desktopSize = desktopPane.getSize();
        System.out.println("Desktop size width= "+desktopSize.width);
        System.out.println("Desktop size height= "+desktopSize.height);
        
        Dimension jInternalFrameSize = jInternalFrame.getSize();
        System.out.println("Component size width= "+jInternalFrameSize.width);
        System.out.println("Component size height= "+jInternalFrameSize.height);
        
        int x =(desktopSize.width - jInternalFrameSize.width)/2;
        int y =(desktopSize.height - jInternalFrameSize.height)/2;
        
        System.out.println("Location x="+x);
        System.out.println("Location y="+y);
        
        jInternalFrame.setLocation(x,y);
        
        desktopPane.add(jInternalFrame).setVisible(true);
    }
}
